=== HalynaChuvaieva/PeriodicalsLab/src/main/resources/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="PeriodicalType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="NEWSPAPER"/>
            <xs:enumeration value="MAGAZINE"/>
            <xs:enumeration value="BOOKLET"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="VolumeType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- підписний індекс 5 цифрр -->
    <xs:simpleType name="SubscriptionIndexType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CharsType">
        <xs:sequence>
            <xs:element name="Colored" type="xs:boolean"/>
            <xs:element name="Volume" type="VolumeType"/>
            <xs:element name="Glossy" type="xs:boolean"/>
            <!-- minOccurs="0" буклети не мають підписного індексу -->
            <xs:element name="SubscriptionIndex" type="SubscriptionIndexType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PeriodicalItemType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element name="Type" type="PeriodicalType"/>
            <xs:element name="Monthly" type="xs:boolean"/>
            <xs:element name="Chars" type="CharsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:element name="Paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Periodical" type="PeriodicalItemType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== HalynaChuvaieva/PeriodicalsLab/src/main/resources/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<Paper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="papers.xsd">

    <Periodical id="p1">
        <Title>Урядовий кур'єр</Title>
        <Type>NEWSPAPER</Type>
        <Monthly>false</Monthly>
        <Chars>
            <Colored>false</Colored>
            <Volume>16</Volume>
            <Glossy>false</Glossy>
            <SubscriptionIndex>12345</SubscriptionIndex>
        </Chars>
    </Periodical>

    <Periodical id="p2">
        <Title>Forbes Ukraine</Title>
        <Type>MAGAZINE</Type>
        <Monthly>true</Monthly>
        <Chars>
            <Colored>true</Colored>
            <Volume>120</Volume>
            <Glossy>true</Glossy>
            <SubscriptionIndex>54321</SubscriptionIndex>
        </Chars>
    </Periodical>

    <Periodical id="p3">
        <Title>ІТ Конференція 2026</Title>
        <Type>BOOKLET</Type>
        <Monthly>false</Monthly>
        <Chars>
            <Colored>true</Colored>
            <Volume>8</Volume>
            <Glossy>true</Glossy>
        </Chars>
    </Periodical>

    <Periodical id="p4">
        <Title>Vogue UA</Title>
        <Type>MAGAZINE</Type>
        <Monthly>true</Monthly>
        <Chars>
            <Colored>true</Colored>
            <Volume>200</Volume>
            <Glossy>true</Glossy>
            <SubscriptionIndex>98765</SubscriptionIndex>
        </Chars>
    </Periodical>
</Paper>
